<a href="https://colab.research.google.com/github/Nmiet1234/RNN/blob/main/Tensor_operations.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

print(torch.__version__)
print(torch.cuda.is_available())


2.6.0+cu124
True


Creating Tensor CPU example

In [2]:
# Import the PyTorch library. This library provides tools for working with tensors
# and building deep learning models. Think of it as a toolbox specifically
# designed for tasks like image recognition or natural language processing.
import torch

# Create the first tensor named 'first_tens'.
# A tensor is like a multi-dimensional array that can hold numbers.
# In this case, we are creating a 2x4 tensor, which means it has 2 rows and 4 columns.
# The numbers inside the double square brackets represent the values in the tensor.
first_tens = torch.tensor([[12, 10, 11, 9], [13, 15, 14, 16]])

# Create the second tensor named 'second_tens'.
# This tensor also has 2 rows and 4 columns, just like 'first_tens'.
# It's filled with different numbers.
second_tens = torch.tensor([[1, 2, 3, 4], [5, 6, 7, 8]])

# Now, let's add the two tensors together.
# This operation is called element-wise addition, which means corresponding elements
# in 'first_tens' and 'second_tens' are added together.
# For example, the first element in 'first_tens' (12) is added to the first element
# in 'second_tens' (1), resulting in 13. This is done for all elements in the tensors.
# The result of this addition is stored in a new tensor called 'add_tens'.
add_tens = first_tens + second_tens

# Let's see what the result looks like!
# This line prints the content of the 'add_tens' tensor, showing the outcome of the addition.
print(add_tens)

# We can also find out the size (dimensions) of the 'add_tens' tensor.
# This line prints the shape of the tensor, which in this case will be 2x4
# (2 rows and 4 columns).
print(add_tens.size())

tensor([[13, 12, 14, 13],
        [18, 21, 21, 24]])
torch.Size([2, 4])


In [ ]:
sub_tens = first_tens - second_tens
print(sub_tens)
print(sub_tens.size())

tensor([[11,  8,  8,  5],
        [ 8,  9,  7,  8]])
torch.Size([2, 4])


Creating tensors GPU example

In [3]:
# Import the PyTorch library. This library provides tools for working with tensors
# and building deep learning models. Think of it as a toolbox specifically
# designed for tasks like image recognition or natural language processing.
import torch

# Print the version of PyTorch that is installed. This is useful for ensuring
# compatibility and reproducibility, as different PyTorch versions might have
# slightly different behaviors or functionalities.
print(torch.__version__)

# Check if a compatible NVIDIA GPU is available for computations.
# If a GPU is available, it assigns the string "cuda" to the 'device' variable,
# indicating that computations should be performed on the GPU.
# If a GPU is not available, it assigns "cpu" to the 'device' variable,
# indicating that computations should be performed on the CPU.
if torch.cuda.is_available():
    device = "cuda"
else:
    device = "cpu"

# Print the chosen device ("cuda" for GPU or "cpu" for CPU).
# This helps confirm where the computations will be executed.
print(device)

# Create the first tensor named 'tens_a'. A tensor is like a multi-dimensional array
# that can hold numbers. This tensor has 2 rows and 4 columns,
# and it is filled with the specified values.
# The 'device=device' argument ensures that the tensor is created on the chosen device
# (either GPU or CPU).
tens_a = torch.tensor([[10, 11, 12, 13], [14, 15, 16, 17]], device=device)

# Create the second tensor named 'tens_b' with similar dimensions and values.
# It is also placed on the chosen device.
tens_b = torch.tensor([[18, 19, 20, 21], [22, 23, 24, 25]], device=device)

# Perform element-wise multiplication between 'tens_a' and 'tens_b'.
# This means that corresponding elements in the two tensors are multiplied together.
# The result is stored in a new tensor called 'multi_tens'.
multi_tens = tens_a * tens_b

# Print the content of 'multi_tens', showing the outcome of the multiplication.
print(multi_tens)

2.6.0+cu124
cuda
tensor([[180, 209, 240, 273],
        [308, 345, 384, 425]], device='cuda:0')


Moving Tensors Between CPUs and GPUs

In [ ]:
# Import the PyTorch library. This library is essential for working with tensors
# and building deep learning models in Python.
import torch

# Create a PyTorch tensor named 'x'.
# A tensor is a fundamental data structure in PyTorch used to store and manipulate numerical data.
# It's similar to a multi-dimensional array (like a NumPy array).
# This tensor is initialized with the values [5, 10, 15, 10, 25].
x = torch.tensor([5, 10, 15, 10, 25])

# Print the content of the tensor 'x' to the console.
# This will display the values stored in the tensor.
print("Tensor:", x)

# Check and print the device where the tensor 'x' is currently stored.
# By default, tensors are created on the CPU (Central Processing Unit).
# The 'device' attribute of a tensor indicates its location (CPU or GPU).
print("Tensor device:", x.device)

# Check if a CUDA-enabled GPU is available on your system.
# CUDA is a parallel computing platform and programming model developed by NVIDIA.
# PyTorch can utilize GPUs for faster computations, especially in deep learning tasks.
# torch.cuda.is_available() returns True if a compatible GPU is found, otherwise False.
print("CUDA GPU:", torch.cuda.is_available())

# If a CUDA GPU is available, move the tensor 'x' to the GPU.
if torch.cuda.is_available():
    # x.to("cuda:0") moves the tensor to the first GPU (index 0).
    # If you have multiple GPUs, you can change the index to select a different GPU.
    x = x.to("cuda:0")
    # Alternatively, you can use x.to("cuda") to move the tensor to the default GPU.

    # Print the content of the tensor 'x' after moving it to the GPU.
    # This might show the GPU location where the tensor is now stored.
    print(x)

# Check and print the device of the tensor 'x' again.
# If it was successfully moved to the GPU, it will now show "cuda:0" (or "cuda").
# If not, it will still indicate "cpu".
print("Tensor device:", x.device)

Tensor: tensor([ 5, 10, 15, 10, 25])
Tensor device: cpu
CUDA GPU: False
Tensor device: cpu


Different ways to create tensors

In [ ]:
# Import the PyTorch library for working with tensors.
import torch

# Import the NumPy library for numerical computations and arrays.
import numpy as np

# Create a tensor from a Python list.
# torch.tensor() is used to create a tensor from various data structures.
tensor_from_list = torch.tensor([1, 2, 3, 4, 5])

# Create a tensor from a Python tuple.
tensor_from_tuple = torch.tensor((6, 7, 8, 9, 10))

# Print the tensor created from the list.
print("Tensor from list:", tensor_from_list)

# Print the tensor created from the tuple.
print("Tensor from tuple:", tensor_from_tuple)

# Create a tensor from a NumPy ndarray.
# np.array() is used to create a NumPy array.
tensor_from_array = torch.tensor(np.array([11, 12, 13, 14, 15]))

# Print the tensor created from the NumPy array.
print("Tensor from array:", tensor_from_array)

Tensor from list: tensor([1, 2, 3, 4, 5])
Tensor from tuple: tensor([ 6,  7,  8,  9, 10])
Tensor from array: tensor([11, 12, 13, 14, 15])


Different functions for creating tensors:

In [ ]:
# Import the PyTorch library. This is the fundamental library for working with tensors in Python.
import torch

# Create an empty tensor with dimensions 3x4.
# torch.empty() allocates memory for the tensor but doesn't initialize its values.
# The tensor will contain whatever garbage data was already in that memory location.
tensor_emp = torch.empty(3, 4)
print("tensor_emp :", tensor_emp)  # Print the content of the empty tensor.

# Create a tensor filled with zeros, with dimensions 3x4.
# torch.zeros() creates a tensor and initializes all its elements to 0.
tensor_zeros = torch.zeros(3, 4)
print("tensor_zeros :", tensor_zeros)  # Print the content of the zero tensor.

# Create a tensor filled with ones, with dimensions 3x4.
# torch.ones() creates a tensor and initializes all its elements to 1.
tensor_ones = torch.ones(3, 4)
print("tensor_ones :", tensor_ones)  # Print the content of the ones tensor.

# --- Creating tensors with random values ---

# Create a tensor with dimensions 4x5, filled with random numbers from a uniform distribution.
# torch.rand() generates random numbers between 0 and 1 (exclusive) for each element.
tensor_rand_un = torch.rand(4, 5)
print("tensor_rand_un :", tensor_rand_un)  # Print the content of the random uniform tensor.

# Create a tensor with dimensions 4x5, filled with random numbers from a normal distribution.
# torch.randn() generates random numbers from a standard normal distribution (mean 0, variance 1).
tensor_rand_norm = torch.randn(4, 5)
print("tensor_rand_norm :", tensor_rand_norm)  # Print the content of the random normal tensor.

# Create a tensor with dimensions 4x5, filled with random integers.
# torch.randint() generates random integers between a specified low (inclusive) and high (exclusive) value.
# In this case, integers will be between 5 (inclusive) and 10 (exclusive).
tensor_rand_int = torch.randint(5, 10, (4, 5))
print("tensor_rand_int :", tensor_rand_int)  # Print the content of the random integer tensor.

# --- Creating a tensor of ones with the same shape as another tensor ---

# Create a tensor filled with ones, having the same shape as tensor_rand_int.
# torch.ones_like() creates a tensor of ones with the same dimensions as the input tensor.
tensor_ones = torch.ones_like(tensor_rand_int)
print(tensor_ones)  # Print the content of the ones tensor (same shape as tensor_rand_int).

tensor_emp : tensor([[6.8177e-12, 4.5454e-41, 6.6580e-12, 4.5454e-41],
        [1.5081e-38, 0.0000e+00, 6.6580e-12, 4.5454e-41],
        [6.6579e-12, 4.5454e-41, 1.1351e-43, 0.0000e+00]])
tensor_zeros : tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor_ones : tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor_rand_un : tensor([[0.3012, 0.0038, 0.9922, 0.7182, 0.2720],
        [0.8498, 0.9267, 0.6300, 0.3709, 0.5736],
        [0.6858, 0.4122, 0.5630, 0.1966, 0.3831],
        [0.0122, 0.3687, 0.3619, 0.5802, 0.0640]])
tensor_rand_norm : tensor([[ 0.3566,  0.3202,  1.9221, -0.0897, -0.9211],
        [ 0.3107, -0.1621, -0.0525,  0.3163, -0.2904],
        [-0.2032, -1.6684, -1.6292, -0.3552,  0.0025],
        [-0.7302,  0.5101, -0.4666, -0.5599,  2.0878]])
tensor_rand_int : tensor([[8, 9, 8, 8, 6],
        [9, 9, 7, 5, 7],
        [9, 9, 6, 8, 6],
        [9, 7, 5, 7, 8]])
tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]


Tensor attributes

knowing device location, datatype, dimension, and rank is very important


In [ ]:
import torch # Imports the PyTorch library, which is essential for working with tensors.

first_tensor = torch.tensor([1,2,3,4,5,6]) # Creates a PyTorch tensor named 'first_tensor' with the given values.

print(first_tensor.device) # Prints the device where the tensor is stored.

print(first_tensor.shape) # Prints the shape of the tensor.

print(first_tensor.ndim) # Prints the number of dimensions (rank) of the tensor.

second_tensor = torch.tensor([[1,2,3],[4,5,6],[7,8,9]]) # Creates another PyTorch tensor, this time with a 2-dimensional structure.

print(second_tensor.dtype) # Prints the data type of the tensor's elements.

print(second_tensor.shape) # Prints the shape of the tensor.

print(second_tensor.ndim) # Prints the number of dimensions (rank) of the tensor.

cpu
torch.Size([6])
1
torch.int64
torch.Size([3, 3])
2
